menu:
  home: /
  archive: /archives
  tags: /tags
  info: /about
  rss: /atom.xml

avatar: /avatar.png
favicon: /favicon.png
aboutme: Beer, Perl, Kansai.pm

social:
  github: http://github.com/nqounet
  twitter: http://twitter.com/nqounet
  facebook: https://www.facebook.com/nobutaka.wakabayashi

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Search

# Analytics
# google-analytics:
ga: UA-3538047-6

# Copyright Infomation
startyear: 2016
