menu:
  home:
      url: /
      icon: home
  archives:
      url: /archives
      icon: archive
  tags:
      url: /tags
      icon: tags
  info:
      url: /about
      icon: info
  feed:
      url: /atom.xml
      icon: rss

avatar: /avatar.png
favicon: /favicon.png
aboutme: Beer, Perl, Kansai.pm

social:
  github: https://github.com/nqounet
  twitter: https://twitter.com/nqounet
  # facebook: https://www.facebook.com/nobutaka.wakabayashi

# Comment
# e.g disqus: seansun
disqus: nqounet
duoshuo:

# Search

# Analytics
# google-analytics:
ga: UA-3538047-6

# Copyright Infomation
startyear: 2000
